socketio/socket.io-client-cpp

src/internal/sio_client_impl.cpp
src/internal/sio_client_impl.h
src/sio_client.h

Fix compilation on GCC

---

src/internal/sio_client_impl.cpp
src/internal/sio_client_impl.h
src/sio_client.cpp
src/sio_client.h

This change allows connect to server with query string.
JavaScript version is like this:
var conn=io(url,query:"token=myToken");

Allow connect to server with query string.

---

src/sio_socket.cpp

Avoid duplicated connection event for default namespace.

---

CMakeLists.txt

I have tried to install this library with TLS, but libsioclient_tls have not installed.
It will fix this issue.

Fix installation issue with TLS

---

README.md
src/internal/sio_packet.cpp
src/sio_message.h

I can't compile the code using gcc 4.8 nor gcc 4.9 on Linux without these fixes.  The virtual destructor on message is straight forward, but I am not sure about the implication of removing const though.  All test cases are passed. Also updated source files listed in README.md.

fix compatibility problem for gcc 4.8+.

---

src/internal/sio_packet.cpp

I've been trying to build the socket IO client using the Android NDK (10e). The NDK misses some std string functions and stoi is one of them. Boost's lexical_cast is functionally equivalent to stoi, so I replaced them. This allowed me to finish the android build.

Use boost::lexical_cast instead of std::stoi for Android compatibility.

---

CMakeLists.txt

For now, socket.io-client-cpp is all static but we could want to choose between static and dynamic.
Furthermore, in some distribution, boost comes only in dynamic.
I propose then to make an option of Boost_USE_STATIC_LIBS (ON by default) and of BUILD_SHARED_LIBS (OFF by default)
By default the behavior will stay the same but we can change with
cmake ../ -DBoost_USE_STATIC_LIBS=OFF -DBUILD_SHARED_LIBS=ON

Add options to choose between static and dynamic libraries

---

src/sio_message.h

cf socketio/socket.io-client-cpp#56

Improved message API

---

src/sio_message.h

Doing so is bad practice. In our case, we override enable_if in our engine, and the compiler got confused.

don't use namespace std in publicly exposed code.

---

README.md

Hi!
While looking into repo, I think I found something strange...like:
Missing brackets in Readme.MD
It looks like a typo. According to source code - https://github.com/socketio/socket.io-client-cpp/blob/f0ed359e0874d1227f17dc6e59bc5f091633764b/src/sio_client.cpp#L82

Missing brackets in Readme File?

---

src/internal/sio_client_impl.cpp
src/internal/sio_client_impl.h
src/sio_client.cpp
src/sio_client.h

Added another overload of client::connect that takes an std::map
of additional HTTP headers to be passed on to the server when connecting.

client: support custom HTTP headers

---

src/internal/sio_client_impl.cpp

This fixes an issue where a disconnect can go undetected.
In the case where `client_impl::send_impl()` continuously gets called with an interval less than `client_impl::m_ping_interval`, a disconnect due to network connectivity problems is never detected because the ping keeps getting delayed by `send_impl()`, thus not allowing a pong timeout to happen, which results in `client_impl::close_impl()` never being called.

Change client_impl::send_impl() not to delay ping

---

src/internal/sio_client_impl.cpp

If any errors occur while closing, such as TLS Short Read, we don't want
to reconnect if we had initiated the close.

Consider all client-initiated closes to be close_reason_normal.

---

examples/Console/main.cpp

bind_events() function used global variable.

Remove unused argument

---

src/internal/sio_client_impl.cpp
src/internal/sio_packet.cpp
src/sio_client.h
src/sio_socket.cpp
src/sio_socket.h

Compiling this muddies up my output with warnings. I'm using gcc 6.3.1 with `-Wall -Wextra -pedantic -std=c++17 -O0 -g`

Remove unused parameters and reorder constructors to get rid of warnings

---

API.md
CMakeLists.txt
src/internal/sio_client_impl.cpp
src/internal/sio_client_impl.h
src/sio_client.cpp
src/sio_client.h

Merge request for reference with the CentOS 7 compatibility fixes and rebased upon the #45 feature.

fix: updates for CentOS 7 support and feature #45

---

src/internal/sio_client_impl.cpp

This allows connection to a socket.io server that is using a path other than `/socket.io/`.

allow resource path to be set in connection URI

---

examples/QT/README.md

Github does not render `###some_title` as a title, so have added a space `### some_title` so the titles are rendered correctly. I'm not sure if this file gets built somehow into a website and if this is to meet those formatting requirements.

Fix the markdown for github

---

src/internal/sio_client_impl.cpp

Most endpoint now deprecate TLSv1 support. Thus we need to enable TLSv2.

Enable tlsv2 when TLS is used

---

src/internal/sio_client_impl.cpp

socket.io-client-cpp is currently hard-coded to use only TLSv1.2. This
commit updates socket.io-client-cpp to use TLSv1.2 or newer.

Support TLSv1.2 and newer

---

src/internal/sio_client_impl.cpp
src/internal/sio_client_impl.h
src/sio_client.cpp
src/sio_client.h
src/sio_socket.cpp
src/sio_socket.h

This allows `sio::client::connect()` to be called with an optional `sio::message::ptr` representing an authentication object, available server-side in the handshake phase (useful when using middlewares with `io.use()`). 
The current alternative is sending authentication info in the query string, which is not a particularly safe practice.
Client code
```cpp
sio::client client;
sio::message::ptr auth = sio::object_message::create();
auth->get_map()["token"] = sio::string_message::create("eyJhbGciOiJIUzI1NiIsInR...");
auth->get_map()["sessionId"] = sio::string_message::create("p0ZoB1FwH6");
// ...
// anything else you might want to send on connection
client.connect(server_url, auth);
```
Server code
```js
const io = SocketIO(server, options);
io.use((socket, next) => {
const { token, …
```

Send authentication info on connection

---

INSTALL.md

The installation instructions don't make it clear that certain preprocessor definitions have to be added in order to build  successfully(https://github.com/socketio/socket.io-client-cpp/issues/313) and that boost is not needed and its inclusion will still cause errors(https://github.com/socketio/socket.io-client-cpp/issues/318, https://github.com/socketio/socket.io-client-cpp/issues/300).
This change just copies the preprocessor definitions from the CMakeLists file to the installation instructions

Make non-cmake installation instructions mimic cmake

---

src/internal/sio_client_impl.cpp
src/internal/sio_client_impl.h

After this commit https://github.com/socketio/socket.io-client-cpp/commit/ec4d540ad54593604ac2091e67ffc2a6d9a00db6 the ping timeout behavior was broken.
Fixes:
* Re-enable ping timeout handling.
* Remove ping function that was unused.

Re-enable ping timeout behaviour for 3x branch

---

src/internal/sio_client_impl.cpp
src/internal/sio_client_impl.h

I've ended up in a deadlock when calling `sync_close` while the network thread is caught in a loop of retrying and failing to connect. This prevents that.

Abort retrying when closing down.

---

src/internal/sio_client_impl.cpp

Same as #134 but for 2.x branch.

allow resource path to be set in connection URI for 2.x

---

.github/workflows/ci.yml
CMakeLists.txt
sioclientConfig.cmake.in

This is a fix for #366 that adds the following features:
1. The cmake configuration files are installed so that `find_package` can resolve them correctly.
2. An option to use system installed libraries instead of the built in modules.

Update cmake for system install

---

.github/workflows/ci.yml
CMakeLists.txt

This PR fixes the following:
- The installation was not working due to installing a file with the wrong name
- The flag `USE_SUBMODULES` was set to `OFF` by default which is a different behaviour from what has been done in the past.

Fix installation and change build default flags

---

src/internal/sio_client_impl.cpp
src/internal/sio_client_impl.h
src/sio_client.cpp
src/sio_client.h

With existing websocketpp interface, I implement to support basic auth proxy.
Usage:
```cpp
sio::client h;
std::string proxy = "http://127.0.0.1:3128/";
h.set_proxy_basic_auth(proxy, "user", "password");
h.connect("http://127.0.0.1:3000");
```

feat: basic auth proxy

---

API.md
src/internal/sio_client_impl.cpp
src/internal/sio_client_impl.h
src/sio_client.cpp
src/sio_client.h
src/sio_socket.cpp
src/sio_socket.h

The choice is made at runtime, if a TLS URI (https:// or wss://) is given, the TLS client will be used, otherwise the non-TLS client will be used.
Additionally, a new constructor is introduced allowing the URI to be passed at construction, which allows the above selection to occur, otherwise only the default for the library (TLS or non-TLS) will be used (preserving the original behavior).

In TLS build of library, support both TLS and non-TLS connections.

---

src/sio_socket.cpp

sio_socket.cpp did not use the `SIO_DISABLE_LOGGING` macro. This PR fixes this.

core: fix logging macro not used in sio_socket.cpp

---

CMakeLists.txt

Sets minimum CMake version to 3.12 and adds maximum to 3.27

build: Bump CMake version

---

src/internal/sio_client_impl.cpp

Sync session id with server

---

.gitignore
src/sio_socket.cpp
src/sio_socket.h

Fixed issue #364
Adding this because someone requested it, and also some web framework like React has some stupid designs, and if a person wants to listen all the components from server, they need to create x listeners, which is ridiculous imo

Add on_any

---

src/sio_message.h

Add std to all move references.
The code does not compile if used externally and no using namespace is references.

Add std to all move references

---

CMakeLists.txt

If it's included too late, the interface directory will not be populated.
Currently:
```
$ cmake -B _builds -D CMAKE_INSTALL_PREFIX=${HOME}/opt/sioclient
$ cmake --build _builds --target install
$ grep INTERFACE_INCLUDE_DIRECTORIES ${HOME}/opt/sioclient/lib/cmake/sioclient/sioclientTargets.cmake || echo FAIL
FAIL
```
As a workaround, `CMAKE_INSTALL_INCLUDEDIR` can be added explicitly:
```
$ cmake -B _builds -D CMAKE_INSTALL_PREFIX=${HOME}/opt/sioclient -D CMAKE_INSTALL_INCLUDEDIR=include
$ cmake --build _builds --target install
$ grep INTERFACE_INCLUDE_DIRECTORIES ${HOME}/opt/sioclient/lib/cmake/sioclient/sioclientTargets.cmake || echo FAIL
INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
```
With this patch:
```
$ cmake …
```

GNUInstallDirs should be included before usage of CMAKE_INSTALL_INCLUDEDIR

---

CMakeLists.txt
examples/Console/CMakeLists.txt
test/CMakeLists.txt

Hello!
We are packaging Socket IO Client in Conan (PR https://github.com/conan-io/conan-center-index/pull/24112/) and we use multiple C++ standards in our CI, including C++11 and newer versions.
We found that Socket IO is using C++11 only, via set_property() in CMakeLists.txt. So, this PR replaces that function by [target_compile_features](https://cmake.org/cmake/help/latest/command/target_compile_features.html), so we can pass `CMAKE_CXX_STANDARD` and override C++11 to something newer like C++14/17/20/23 (set_property() does not allow override).
Plus, I updated [threads](https://cmake.org/cmake/help/latest/module/FindThreads.html) requirement in the project:
- sio_test.cpp uses thread
- sio_client_impl.h uses thread. It should be public because is listed in the header.
- …

Allow using new C++ standards when building

---

CMakeLists.txt
INSTALL.md
README.md

Hello!
In this PR I tried new changes that I hope be useful for users, including:
- Before the PR #406, the FATAL_ERROR in CMakeLists.txt version was related to avoid running older versions. Later, was added a maximum CMake version, but the CMake is very compatible between a version and other, so I removed the FATAL_ERROR to allow running the latest CMake version available (3.29.x)
- When consuming Asio, both CMake target (asio::asio) and the library asio are consumed, causing double inclusion. I removed the library to keep CMake target are preference.
- After merging the PR https://github.com/conan-io/conan-center-index/pull/24176 in ConanCenterIndex, the socket-io client cpp is now available in Conan Center (https://conan.io/center/recipes/sioclient?version=cci.20240405) and can be …

Flexibilize CMake version and add Conan steps in docs

---

src/sio_message.h

* Add overrides
* Remove shadowing
This is a dependency of a project I'm fixing up, and I was getting some warnings, so I have fixed them
:D

Fix warnings in sio_message.h
